GameStore.Web/Controllers/CartController.cs
using GameStore.Domain.Abstract;
using GameStore.Domain.Entities;
using GameStore.Web.Models;
using GameStore.Web.Services.Abstract;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace GameStore.Web.Controllers
{
    namespace GameStore.Web.Controllers
    {
        public class CartController : Controller
        {
            private readonly IGameRepository _repository;
            private readonly IOrderProcessor _orderProcessor;
            private readonly ICartProvider _cartProvider;

            public CartController(IGameRepository repo, IOrderProcessor processor, ICartProvider cartProvider)
            {
                _repository = repo;
                _orderProcessor = processor;
                _cartProvider = cartProvider;
            }

            public IActionResult Checkout()
            {
                return View(new ShippingDetails());
            }

            [HttpPost]
            public IActionResult Checkout(ShippingDetails shippingDetails)
            {
                if (_cartProvider.Lines.Count() == 0)
                {
                    ModelState.AddModelError("", "Извините, ваша корзина пуста!");
                }

                if (ModelState.IsValid)
                {
                    _orderProcessor.ProcessOrder(shippingDetails);
                    _cartProvider.Clear();
                    return View("Completed");
                }
                else
                {
                    return View(shippingDetails);
                }
            }

            public IActionResult Index(string returnUrl)
            {
                return View(new CartIndexViewModel
                {
                    Lines = _cartProvider.Lines.ToList(),
                    ReturnUrl = returnUrl,
                    TotalValue = _cartProvider.ComputeTotalValue()
                });
            }

            public async Task<IActionResult> AddToCart(int gameId, string returnUrl)
            {
                Game game = await _repository.FindAsync(gameId);

                if (game != null)
                {
                     _cartProvider.AddItem(game, 1);
                }
                return RedirectToAction("Index", new { returnUrl });
            }

            public async Task<IActionResult> RemoveFromCart(int gameId, string returnUrl)
            {
                Game game = await _repository.FindAsync(gameId);

                if (game != null)
                {
                    _cartProvider.RemoveLine(game);
                }
                return RedirectToAction("Index", new { returnUrl });
            }
          
        }
    }
}

GameStore.Web/Controllers/GameController.cs
using GameStore.Domain.Abstract;
using GameStore.Domain.Entities;
using GameStore.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace GameStore.Web.Controllers
{
    public class GameController : Controller
    {
        private IGameRepository repository;
        public int pageSize = 4;

        public GameController(IGameRepository repo)
        {
            repository = repo;
        }

        public async Task<IActionResult> List(string category, int page = 1)
        {
            GamesListViewModel model = new GamesListViewModel
            {
                Games = repository.GetByCategory(category, page, pageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = category == null ?
              await  repository.GetCountAsync() :
              await  repository.GetCountByCategoryAsync(category)
                },
                CurrentCategory = category
            };
            return View(model);
        }
        public async Task<IActionResult> GetImage(int gameId)
        {
            Game game = await repository.FindAsync(gameId);
            if (game != null)
            {
                return File(game.ImageData, game.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
    }
}

GameStore.Web/Views/Shared/GameSummary.cshtml
@model GameStore.Domain.Entities.Game

<div class="well">
    @if (Model.ImageData != null)
    {
        <div class="pull-left" style="margin-right: 10px">
            <img class="img-thumbnail" width="75" height="75"
                 src="@Url.Action("GetImage", "Game",
                new { Model.GameId })" />
        </div>
    }

    <h3>
        <strong>@Model.Name</strong>
        <span class="pull-right label label-primary">@Model.Price.ToString("# руб")</span>
    </h3>
    @using (Html.BeginForm("AddToCart", "Cart"))
    {
        <div class="pull-right">
            @Html.HiddenFor(x => x.GameId)
            @Html.Hidden("returnUrl", Context.Request.Path)
            <input type="submit" class="btn btn-success" value="Добавить в корзину" />
        </div>
    }
    <span class="lead">@Model.Description</span>
</div>

GameStore.Web/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.9.1.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <title></title>
</head>
<body>
    <div>
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
</body>
</html>

GameStore.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="#">GameStore - магазин компьютерных игр</a>
        @await Component.InvokeAsync("CartSummary")
    </div>
    <div class="row panel">
        <div id="categories" class="col-xs-3">
            @await Component.InvokeAsync("SideMenu")
        </div>
        <div class="col-xs-8">
            @RenderBody()
        </div>
    </div>
</body>
</html>